// <auto-generated />
namespace Ticket.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create20180207 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create20180207));
        
        string IMigrationMetadata.Id
        {
            get { return "201802070342263_create20180207"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
