// <auto-generated />
namespace Ticket.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create20180211 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create20180211));
        
        string IMigrationMetadata.Id
        {
            get { return "201802110801308_create20180211"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
